version: '3'

networks:
  front:
    driver: bridge
  back:
    driver: bridge

services:
  # ===== begin: mysql =====
  mysql:
    container_name: ${APP_ID:-app}_mysql
    build:
      context: ./containers/mysql
      dockerfile: Dockerfile
      args:
        MYSQL_CONTAINER_DATA_PATH: ${MYSQL_CONTAINER_DATA_PATH:-/data}
    image: axelitus/laramesh_mysql:0.0.1
    environment:
      APP_OWNER_GID: ${APP_OWNER_GID:-1000}
      APP_OWNER_UID: ${APP_OWNER_UID:-1000}
      MYSQL_CREATE_SCHEMA: ${MYSQL_CREATE_SCHEMA:-}
      MYSQL_CONTAINER_DATA_PATH: ${MYSQL_CONTAINER_DATA_PATH:-/data}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER:-laramesh}
    ports:
      - ${HOST_PORT_BIND_MYSQL:-33060}:3306
    volumes:
      - ${MYSQL_DATA_SRC:-./data/mysql}:${MYSQL_CONTAINER_DATA_PATH:-/data}
    networks:
      - back
  # ===== end: mysql =====
  # ===== begin: nginx =====
  nginx:
    container_name: ${APP_ID:-app}_nginx
    build:
      context: ./containers/nginx
      dockerfile: Dockerfile
      args:
        APP_CONTAINER_PATH: ${APP_CONTAINER_PATH:-app}
    image: axelitus/laramesh_nginx:0.0.1
    depends_on:
      - php
    environment:
      APP_OWNER_GID: ${APP_OWNER_GID:-1000}
      APP_OWNER_UID: ${APP_OWNER_UID:-1000}
      APP_CONTAINER_PATH: ${APP_CONTAINER_PATH:-/app}
      APP_ROOT_SUBPATH: ${APP_ROOT_SUBPATH:-/public}
    ports:
      - ${HOST_PORT_BIND_NGINX:-8000}:80
    volumes:
      - ${APP_SRC:-./app}:${APP_CONTAINER_PATH:-/app}
    networks:
      - front
  # ===== end: nginx =====
  # ===== begin: php =====
  php:
    container_name: ${APP_ID:-app}_php
    build:
      context: ./containers/php
      dockerfile: Dockerfile
      args:
        APP_CONTAINER_PATH: ${APP_CONTAINER_PATH:-/app}
    image: axelitus/laramesh_php:0.0.1
    depends_on:
      - mysql
    environment:
      APP_OWNER_GID: ${APP_OWNER_GID:-1000}
      APP_OWNER_UID: ${APP_OWNER_UID:-1000}
      APP_CONTAINER_PATH: ${APP_CONTAINER_PATH:-/app}
    ports:
      - ${HOST_PORT_BIND_PHP_FPM:-9000}:9000
    volumes:
      - ${APP_SRC:-./app}:${APP_CONTAINER_PATH:-/app}
    networks:
      - back
      - front
  # ===== end: php =====
